### ISSUE TITLE
npm init riot not working, type error

### ISSUE THREAD

**Issue by luisarmada** [riot/create-riot#14]
TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
    at $o (/dcs/22/u2202567/.npm/_npx/91a95858ebf364cb/node_modules/esm/esm.js:1:224377)
    at wu (/dcs/22/u2202567/.npm/_npx/91a95858ebf364cb/node_modules/esm/esm.js:1:227324)
    at Eu (/dcs/22/u2202567/.npm/_npx/91a95858ebf364cb/node_modules/esm/esm.js:1:227999)
    at Module.<anonymous> (/dcs/22/u2202567/.npm/_npx/91a95858ebf364cb/node_modules/esm/esm.js:1:295976)
    at n (/dcs/22/u2202567/.npm/_npx/91a95858ebf364cb/node_modules/esm/esm.js:1:279589)
    at Object.<anonymous> (/dcs/22/u2202567/.npm/_npx/91a95858ebf364cb/node_modules/create-riot/index.js:6:23)
    at Module._compile (node:internal/modules/cjs/loader:1434:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
    at Module.load (node:internal/modules/cjs/loader:1249:32)
    at Module._load (node:internal/modules/cjs/loader:1065:12)

Node.js v22.2.0
npm error code 1
npm error path /dcs/22/u2202567/Documents/web2/imaginaryfight
npm error command failed
npm error command sh -c create-riot

**Comment by GianlucaGuarini** [comment]
Thank you for reporting this issue. The new major version solves this problem

**Comment by GianlucaGuarini** [comment]
It seems that there is still a bit of work to do. I will reopen this issue since node 22 can't copy the template folders yet :(

**Comment by GianlucaGuarini** [comment]
This issue was completely fixed with this version https://github.com/riot/create-riot/releases/tag/v3.0.2 thank you
