### ISSUE TITLE
Error during npm init riot

### ISSUE THREAD

**Issue by rudinandrey** [riot/create-riot#8]
`npm init riot
npm WARN exec The following package was not found and will be installed: create-riot
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help init` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (apps)
version: (1.0.0)
description:
git repository:
keywords:
author:
license: (ISC)
About to write to C:\projects\riot\apps\package.json:

{
  "name": "apps",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}

√ Please select a template · webpack
- Downloading the template files

It was not possible to download the template zip file
Error details:

C:\Users\rudin\AppData\Local\npm-cache\_npx\939675aa98f97328\node_modules\create-riot\src\utils.js:38
  throw new Error(error)
        ^

Error: StatusCodeError: 404 - {"type":"Buffer","data":[52,48,52,58,32,78,111,116,32,70,111,117,110,100]}
    at panic (C:\Users\rudin\AppData\Local\npm-cache\_npx\939675aa98f97328\node_modules\create-riot\src\utils.js:38:9)
    at downloadFile (C:\Users\rudin\AppData\Local\npm-cache\_npx\939675aa98f97328\node_modules\create-riot\src\utils.js:84:5)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async download (C:\Users\rudin\AppData\Local\npm-cache\_npx\939675aa98f97328\node_modules\create-riot\src\index.js:27:19)
    at async Proxy.main (C:\Users\rudin\AppData\Local\npm-cache\_npx\939675aa98f97328\node_modules\create-riot\src\index.js:109:19)
npm ERR! code 1
npm ERR! path C:\projects\riot\apps
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-riot

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rudin\AppData\Local\npm-cache\_logs\2021-06-14T09_53_08_551Z-debug.log
`

**Comment by rudinandrey** [comment]
I was local problem. I run cmd under administrator, npm cache clean --force and npm install -g create-riot and all works. Thanks!
